### ISSUE TITLE
Field selection for /extras extension point

### ISSUE THREAD

**Issue by nuest** [52North/sensorweb-rest-api#105]
The `/extras` endpoint should get a possibility for subsetting the top level fields to allow handling a large number of extension points or to handle extension points which provide large responses.

Full extra information: `../timeseries/id_001/extras`:

```json
{
    "fieldA":"somedata",
    "fieldB":1.1,
    "fieldC":{
        "subfields":true,
        "subfield2":42,
        "evenmorestuff": { [...] }
    }
}
```

Selected extra information: `../timeseries/id_001/extras?fields=fieldA,fieldB`

```json
{
    "fieldA":"somedata",
    "fieldB":1.1
}
```

The name should be discussed, could also be "subset", or "select".

**Comment by ridoo** [comment]
Nice one! Yes, this would make sense but also for the whole API.

**Comment by nuest** [comment]
Yes, this would also word as a common query parameter.

**Comment by ridoo** [comment]
I created issue #169 because of the comment above. this issue is closed.
