### ISSUE TITLE
timeseries-api and sos version 1.0

### ISSUE THREAD

**Issue by lottaa** [52North/sensorweb-rest-api#99]
Is it possible to use timeseries-api with older sos version 1.0 and sos data model?

**Comment by ridoo** [comment]
@lottaa the REST API just defines a thin access layer to actually any kind of in-situ timeseries data. SOS services of specification 1.0.0 and 2.0.0 are supported by the SPI implementation of the https://github.com/52North/SensorWebClient.

However, the `SensorWebClient is a quite heavy dependency so the core parts needed to access SOS services are assembled in the http://github.com/52North/restful-timeseries-proxy.  You can just clone and build it via Maven. Make sure to edit [the sos-instances.data.xml](https://github.com/52North/restful-timeseries-proxy/blob/master/webapp/src/main/webapp/ds/sos-instances.data.xml) to your needs to access the SOS instance(s) you want.

**Comment by ridoo** [comment]
But only the series data model is supported which comes with 52n SOS implementations since version 4.x

**Comment by lottaa** [comment]
That means if I would like to have output formats like JSON for my timeseries data, I have to use the sos database model since version 4.x?

**Comment by ridoo** [comment]
No. You can configure the proxy component to work with all SOS instances. The API will request the SOS via its standardized interface and translates output to JSON [as defined by the API](http://52north.github.io/timeseries-api/).

However, if this leads to performance issues (marshalling/unmarshalling) you should go for the newer SOS 4.x instance and configure the REST API to directly read from the (same) database. 

If for some use cases you have to provide full flexibility of the SOS but also have to come up with a lightweight variant like a mobile device REST client (like the 52°North [JavaScript client solution](https://github.com/52North/js-sensorweb-client)) this is the way to go.

Alternatively you could set up an SOS and just access it via [the SOS JavaScript lib](https://github.com/52North/sos-js) which directly queries data from the SOS interface. I do not know how the performance works out when browsers parsing XML via JavaScript, though

**Comment by nuest** [comment]
@lottaa Are all your questions answered?

**Comment by ridoo** [comment]
I close this issue due to inactivity
